annotations:
  category: DeveloperTools
apiVersion: v2
appVersion: 0.7.5
description: ExternalDNS is a Kubernetes addon that configures public DNS servers with information about exposed Kubernetes services to make them discoverable.
engine: gotpl
keywords:
  - external-dns
  - network
  - dns
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
name: external-dns
version: 4.5.1
