annotations:
  category: Analytics
apiVersion: v2
appVersion: 1.9.7
description: kube-state-metrics is a simple service that listens to the Kubernetes API server and generates metrics about the state of the objects.
engine: gotpl
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
keywords:
  - prometheus
  - kube-state-metrics
  - monitoring
name: kube-state-metrics
version: 1.1.4
